### ISSUE TITLE
DB terminology and consistency

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#61]
Suggestion (please comment below):

- rename "_ID" in all fieldnames to lowercase "_id"
- rename table "keywords" to "topic_recommendations" (the list of topics will be in table "topics")
- rename table "keyword_feedback" to "topic_feedback"
  - the value of feedback should be an ENUM (APPROVE, REJECT) instead of a VARCHAR
- rename table "system_recommendations" to "article_recommendations"
- rename table "user_recommendations" to "article_feedback"
- drop table "user_webpages" and have dedicated fields for each type of webpage in the "users" table

**Comment by oyvi96** [comment]
- rename "_ID" in all fieldnames to lowercase "_id"
  - Probably smart will do. 
- rename table "keywords" to "topic_recommendations" (the list of topics will be in table "topics")
  - Topics have changes so much since the initial implementation that it will probably be easier to drop the topic related tables and recreate them with the correct columns, as even if we kept the current data, there would be so many empty or wrong fields that it would only make a mess, we haven't even collected any topics yet on gustav.
- rename table "keyword_feedback" to "topic_feedback"
  - The same as with the table above.
  - the value of feedback should be an ENUM (APPROVE, REJECT) instead of a VARCHAR
    - Should use enums, may be some other places where we could benefit from enums too. 

- rename table "system_recommendations" to "article_recommendations"
  - Will do.
- rename table "user_recommendations" to "article_feedback"
  - Will do.
- drop table "user_webpages" and have dedicated fields for each type of webpage in the "users" table
  - Was the plan with the changes to how webpages work.

**Comment by kbalog** [comment]
- OK, regarding dropping the old "keyword*" tables and creating new "topic*" tables.
- Yes, generally use ENUMs instead of VARCHARs where there is a small set of possible values.

Let's keep this issue open until all these changes have taken place.

**Comment by kbalog** [comment]
When doing the renaming of "_ID" fields, it would also be good to check the indices on all tables (and make sure that fields that are present in WHERE clauses of SQL queries are indexed).

**Comment by oyvi96** [comment]
also add timestamp to feedback
